import { StandardCategory, VulnerabilityCheck, Severity } from "./types";

export const STANDARDS: Record<StandardCategory, { label: string; description: string; color: string }> = {
  OWASP_TOP10:  { label: "OWASP Top 10",   description: "Most critical web application security risks (2021)",     color: "bg-red-500/10 text-red-400 border-red-500/20" },
  OWASP_API:    { label: "OWASP API Top 10",description: "API-specific security risks (2023)",                      color: "bg-orange-500/10 text-orange-400 border-orange-500/20" },
  CWE:          { label: "CWE / MITRE",     description: "Common Weakness Enumeration",                             color: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20" },
  SANS_TOP25:   { label: "SANS Top 25",     description: "Most dangerous software errors",                          color: "bg-purple-500/10 text-purple-400 border-purple-500/20" },
  NIST:         { label: "NIST SP 800-53",  description: "Security and privacy controls for information systems",   color: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  PCI_DSS:      { label: "PCI-DSS",         description: "Payment Card Industry Data Security Standard",            color: "bg-green-500/10 text-green-400 border-green-500/20" },
  GDPR:         { label: "GDPR",            description: "General Data Protection Regulation compliance",           color: "bg-teal-500/10 text-teal-400 border-teal-500/20" },
  ISO27001:     { label: "ISO 27001",       description: "Information security management systems",                 color: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20" },
};

export const SEVERITY_CONFIG: Record<Severity, { label: string; color: string; bg: string; border: string; dot: string }> = {
  critical: { label: "Critical", color: "text-red-400",    bg: "bg-red-500/10",    border: "border-red-500/30",    dot: "bg-red-500" },
  high:     { label: "High",     color: "text-orange-400", bg: "bg-orange-500/10", border: "border-orange-500/30", dot: "bg-orange-500" },
  medium:   { label: "Medium",   color: "text-yellow-400", bg: "bg-yellow-500/10", border: "border-yellow-500/30", dot: "bg-yellow-500" },
  low:      { label: "Low",      color: "text-blue-400",   bg: "bg-blue-500/10",   border: "border-blue-500/30",   dot: "bg-blue-500" },
  info:     { label: "Info",     color: "text-slate-400",  bg: "bg-slate-500/10",  border: "border-slate-500/30",  dot: "bg-slate-500" },
};

export const VULNERABILITY_CHECKS: VulnerabilityCheck[] = [
  {
    id: "A01",
    name: "Broken Access Control",
    description: "Restrictions on authenticated users not properly enforced",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25", "PCI_DSS"],
    references: ["CWE-284", "CWE-285", "CWE-639"],
    severity: "critical",
    category: "Access Control",
  },
  {
    id: "A02",
    name: "Cryptographic Failures",
    description: "Failures related to cryptography exposing sensitive data",
    standards: ["OWASP_TOP10", "CWE", "PCI_DSS", "GDPR", "NIST"],
    references: ["CWE-259", "CWE-327", "CWE-331"],
    severity: "high",
    category: "Cryptography",
  },
  {
    id: "A03",
    name: "Injection (SQL, XSS, Command)",
    description: "User-supplied data sent to interpreter as part of a command",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25", "PCI_DSS"],
    references: ["CWE-79", "CWE-89", "CWE-78"],
    severity: "critical",
    category: "Injection",
  },
  {
    id: "A04",
    name: "Insecure Design",
    description: "Risks related to design and architectural flaws",
    standards: ["OWASP_TOP10", "NIST", "ISO27001"],
    references: ["CWE-209", "CWE-256", "CWE-501"],
    severity: "high",
    category: "Design",
  },
  {
    id: "A05",
    name: "Security Misconfiguration",
    description: "Improperly configured permissions, unnecessary features enabled",
    standards: ["OWASP_TOP10", "CWE", "NIST", "PCI_DSS", "ISO27001"],
    references: ["CWE-16", "CWE-611"],
    severity: "high",
    category: "Configuration",
  },
  {
    id: "A06",
    name: "Vulnerable & Outdated Components",
    description: "Components with known vulnerabilities",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    references: ["CWE-1026", "CWE-1035", "CWE-1104"],
    severity: "high",
    category: "Dependencies",
  },
  {
    id: "A07",
    name: "Authentication Failures",
    description: "Authentication and session management weaknesses",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25", "PCI_DSS", "NIST"],
    references: ["CWE-287", "CWE-384"],
    severity: "critical",
    category: "Authentication",
  },
  {
    id: "A08",
    name: "Software & Data Integrity Failures",
    description: "Code and infrastructure without integrity verification",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    references: ["CWE-502", "CWE-829"],
    severity: "high",
    category: "Integrity",
  },
  {
    id: "A09",
    name: "Security Logging & Monitoring Failures",
    description: "Insufficient logging and monitoring",
    standards: ["OWASP_TOP10", "NIST", "PCI_DSS", "ISO27001"],
    references: ["CWE-117", "CWE-223", "CWE-532"],
    severity: "medium",
    category: "Logging",
  },
  {
    id: "A10",
    name: "Server-Side Request Forgery (SSRF)",
    description: "Server fetching remote resource without validating user-supplied URL",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25"],
    references: ["CWE-918"],
    severity: "high",
    category: "SSRF",
  },
  {
    id: "API1",
    name: "Broken Object Level Authorization",
    description: "APIs expose endpoints that handle object identifiers without proper authorization",
    standards: ["OWASP_API", "CWE"],
    references: ["CWE-284"],
    severity: "critical",
    category: "API Security",
  },
  {
    id: "API2",
    name: "Broken Authentication (API)",
    description: "Weak authentication mechanisms in APIs",
    standards: ["OWASP_API", "CWE", "NIST"],
    references: ["CWE-287"],
    severity: "critical",
    category: "API Security",
  },
  {
    id: "API3",
    name: "Broken Object Property Level Authorization",
    description: "API exposing more object properties than needed",
    standards: ["OWASP_API", "CWE"],
    references: ["CWE-213", "CWE-915"],
    severity: "high",
    category: "API Security",
  },
  {
    id: "SANS1",
    name: "Buffer Overflow",
    description: "Writing data beyond allocated buffer boundaries",
    standards: ["SANS_TOP25", "CWE"],
    references: ["CWE-120", "CWE-119"],
    severity: "critical",
    category: "Memory Safety",
  },
  {
    id: "TLS1",
    name: "Weak TLS Configuration",
    description: "Outdated TLS versions, weak cipher suites, missing HSTS",
    standards: ["CWE", "NIST", "PCI_DSS", "GDPR"],
    references: ["CWE-326", "CWE-327"],
    severity: "high",
    category: "Transport Security",
  },
  {
    id: "HDR1",
    name: "Missing Security Headers",
    description: "Missing CSP, X-Frame-Options, X-Content-Type-Options, etc.",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    references: ["CWE-693"],
    severity: "medium",
    category: "Headers",
  },
  {
    id: "CSRF1",
    name: "Cross-Site Request Forgery (CSRF)",
    description: "Forging requests on behalf of authenticated users",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25"],
    references: ["CWE-352"],
    severity: "high",
    category: "CSRF",
  },
  {
    id: "GDPR1",
    name: "Cookie Consent & Privacy",
    description: "Missing cookie consent, insecure cookies, data exposure",
    standards: ["GDPR", "PCI_DSS"],
    references: ["GDPR Art. 7", "GDPR Art. 13"],
    severity: "medium",
    category: "Privacy",
  },
  {
    id: "INFO1",
    name: "Information Disclosure",
    description: "Server banners, stack traces, directory listing, comments",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    references: ["CWE-200", "CWE-209"],
    severity: "low",
    category: "Information Disclosure",
  },
  {
    id: "OPEN1",
    name: "Open Redirect",
    description: "Unvalidated redirects and forwards",
    standards: ["CWE", "OWASP_TOP10"],
    references: ["CWE-601"],
    severity: "medium",
    category: "Redirect",
  },
];

export const SCAN_PHASES = [
  "DNS & TLS Reconnaissance",
  "Header & Configuration Analysis",
  "Spider & Crawling",
  "Active Payload Testing",
  "Authentication Analysis",
  "API Endpoint Discovery",
  "Dependency Fingerprinting",
  "Privacy & Compliance Checks",
  "Report Generation",
];

export const GRADE_CONFIG = {
  A: { color: "text-green-400",  bg: "bg-green-500/10",  label: "Excellent" },
  B: { color: "text-blue-400",   bg: "bg-blue-500/10",   label: "Good" },
  C: { color: "text-yellow-400", bg: "bg-yellow-500/10", label: "Fair" },
  D: { color: "text-orange-400", bg: "bg-orange-500/10", label: "Poor" },
  F: { color: "text-red-400",    bg: "bg-red-500/10",    label: "Failing" },
};
