import { ScanResult, Finding } from "./types";

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "f1",
    checkId: "A03",
    title: "Reflected XSS in Search Parameter",
    severity: "critical",
    category: "Injection",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25"],
    url: "https://example.com/search?q=<script>alert(1)</script>",
    parameter: "q",
    evidence: "Response contains unescaped: <script>alert(1)</script>",
    description: "The search parameter is reflected in the HTML response without proper encoding, allowing attackers to inject arbitrary JavaScript.",
    impact: "An attacker can steal session cookies, redirect users to malicious sites, perform actions on behalf of victims, or deface the page.",
    remediation: "Encode all user-supplied input before rendering in HTML. Use context-aware output encoding (HTML entity encoding for HTML context). Implement a Content Security Policy (CSP).",
    codeExample: "// Vulnerable\nres.send(`<p>Results for: ${req.query.q}</p>`);\n\n// Fixed\nimport { escape } from 'html-escaper';\nres.send(`<p>Results for: ${escape(req.query.q)}</p>`);",
    references: ["https://owasp.org/www-community/attacks/xss/", "https://cwe.mitre.org/data/definitions/79.html"],
    cvss: 8.8,
    cwe: "CWE-79",
  },
  {
    id: "f2",
    checkId: "A03",
    title: "SQL Injection in Login Endpoint",
    severity: "critical",
    category: "Injection",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25", "PCI_DSS"],
    url: "https://example.com/api/auth/login",
    parameter: "username",
    evidence: "Payload `' OR 1=1 --` returned 200 OK with valid session token",
    description: "The login endpoint constructs SQL queries using unsanitized user input, enabling attackers to bypass authentication or extract the entire database.",
    impact: "Complete database compromise. Attacker can bypass authentication, read sensitive user data, modify records, or drop tables.",
    remediation: "Use parameterized queries or prepared statements exclusively. Never concatenate user input into SQL strings.",
    codeExample: "// Vulnerable\nconst query = `SELECT * FROM users WHERE username='${username}'`;\n\n// Fixed\nconst query = 'SELECT * FROM users WHERE username = $1';\nawait db.query(query, [username]);",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection", "https://cwe.mitre.org/data/definitions/89.html"],
    cvss: 9.8,
    cwe: "CWE-89",
  },
  {
    id: "f3",
    checkId: "TLS1",
    title: "TLS 1.0 and 1.1 Enabled",
    severity: "high",
    category: "Transport Security",
    standards: ["CWE", "NIST", "PCI_DSS"],
    url: "https://example.com",
    evidence: "Server accepted TLS 1.0 handshake. Cipher: TLS_RSA_WITH_RC4_128_SHA",
    description: "The server supports TLS 1.0 and 1.1 which are deprecated protocols with known vulnerabilities including POODLE and BEAST attacks.",
    impact: "Man-in-the-middle attacks can decrypt HTTPS traffic. PCI-DSS compliance violation. Modern browsers may show security warnings.",
    remediation: "Disable TLS 1.0 and 1.1. Enable only TLS 1.2 and TLS 1.3. Configure strong cipher suites. Enable HSTS with includeSubDomains.",
    references: ["https://nvd.nist.gov/vuln/detail/CVE-2014-3566", "https://www.pcicomplianceguide.org/tls/"],
    cvss: 7.5,
    cwe: "CWE-327",
  },
  {
    id: "f4",
    checkId: "HDR1",
    title: "Missing Content Security Policy Header",
    severity: "medium",
    category: "Headers",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    url: "https://example.com",
    evidence: "HTTP response missing Content-Security-Policy header",
    description: "No Content Security Policy is defined, leaving the application vulnerable to XSS and data injection attacks.",
    impact: "Without CSP, any injected scripts execute without restriction. Increases severity of XSS vulnerabilities significantly.",
    remediation: "Implement a strict CSP header. Start with report-only mode, then enforce.",
    codeExample: "// Express.js example\napp.use((req, res, next) => {\n  res.setHeader(\n    'Content-Security-Policy',\n    \"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'\"\n  );\n  next();\n});",
    references: ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"],
    cvss: 6.1,
    cwe: "CWE-693",
  },
  {
    id: "f5",
    checkId: "A07",
    title: "No Account Lockout on Login",
    severity: "high",
    category: "Authentication",
    standards: ["OWASP_TOP10", "CWE", "NIST", "PCI_DSS"],
    url: "https://example.com/api/auth/login",
    evidence: "500 login attempts made in 60 seconds with no rate limiting or lockout triggered",
    description: "The application does not implement account lockout or rate limiting on the login endpoint, enabling brute-force attacks.",
    impact: "Attackers can conduct unlimited brute-force attacks against user accounts, especially dangerous for accounts with weak passwords.",
    remediation: "Implement rate limiting (e.g., 5 attempts per 15 minutes). Lock accounts temporarily after repeated failures. Add CAPTCHA after 3 failed attempts. Use multi-factor authentication.",
    references: ["https://owasp.org/www-project-web-security-testing-guide/", "https://cwe.mitre.org/data/definitions/307.html"],
    cvss: 7.3,
    cwe: "CWE-307",
  },
  {
    id: "f6",
    checkId: "A01",
    title: "Insecure Direct Object Reference (IDOR)",
    severity: "critical",
    category: "Access Control",
    standards: ["OWASP_TOP10", "CWE", "SANS_TOP25", "OWASP_API"],
    url: "https://example.com/api/users/1234/profile",
    parameter: "userId",
    evidence: "Authenticated as user 9999, successfully accessed /api/users/1234/profile with full PII",
    description: "The API exposes user profile data based solely on the user ID in the URL without verifying the requesting user's authorization.",
    impact: "Any authenticated user can access any other user's private data including PII, leading to data breach and GDPR violations.",
    remediation: "Verify that the authenticated user owns the requested resource. Use indirect references or UUIDs instead of sequential IDs.",
    references: ["https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control"],
    cvss: 8.1,
    cwe: "CWE-639",
  },
  {
    id: "f7",
    checkId: "GDPR1",
    title: "Session Cookie Missing Secure & HttpOnly Flags",
    severity: "medium",
    category: "Privacy",
    standards: ["GDPR", "PCI_DSS", "OWASP_TOP10"],
    url: "https://example.com",
    evidence: "Set-Cookie: session=abc123; Path=/  (missing Secure; HttpOnly; SameSite flags)",
    description: "Session cookies are set without Secure, HttpOnly, or SameSite flags, making them accessible to JavaScript and transmittable over HTTP.",
    impact: "XSS attacks can steal session cookies. Cookies sent over unencrypted connections. CSRF attacks more feasible.",
    remediation: "Set all session cookies with Secure, HttpOnly, and SameSite=Strict or SameSite=Lax flags.",
    codeExample: "res.cookie('session', token, {\n  httpOnly: true,\n  secure: true,\n  sameSite: 'strict',\n  maxAge: 3600000\n});",
    references: ["https://owasp.org/www-community/controls/SecureCookieAttribute"],
    cvss: 6.5,
    cwe: "CWE-614",
  },
  {
    id: "f8",
    checkId: "INFO1",
    title: "Server Version Disclosed in Headers",
    severity: "low",
    category: "Information Disclosure",
    standards: ["OWASP_TOP10", "CWE", "NIST"],
    url: "https://example.com",
    evidence: "Server: Apache/2.4.41 (Ubuntu), X-Powered-By: Express 4.17.1",
    description: "HTTP response headers reveal the web server software and version, aiding attackers in identifying known vulnerabilities.",
    impact: "Provides attackers with specific version information to look up known CVEs and craft targeted exploits.",
    remediation: "Remove or spoof Server and X-Powered-By headers. Configure server to suppress version information.",
    references: ["https://cwe.mitre.org/data/definitions/200.html"],
    cvss: 4.3,
    cwe: "CWE-200",
  },
];

export const MOCK_SCAN_RESULT: ScanResult = {
  id: "scan_demo_001",
  targetUrl: "https://example.com",
  startedAt: new Date(Date.now() - 420000).toISOString(),
  completedAt: new Date(Date.now() - 60000).toISOString(),
  status: "complete",
  config: {
    targetUrl: "https://example.com",
    scanDepth: "standard",
    selectedStandards: ["OWASP_TOP10", "OWASP_API", "CWE", "SANS_TOP25", "NIST", "PCI_DSS", "GDPR"],
    includeAuthenticated: false,
    crawlSubdomains: false,
    maxRequests: 1000,
    timeout: 30,
    userAgent: "SecureApp Scanner/1.0",
  },
  progress: {
    phase: "Complete",
    current: 9,
    total: 9,
    currentUrl: "",
    checksCompleted: [],
    checksRunning: [],
  },
  findings: MOCK_FINDINGS,
  summary: {
    critical: 3,
    high: 3,
    medium: 2,
    low: 1,
    info: 0,
    total: 9,
    score: 34,
    grade: "F",
  },
  pagesScanned: 47,
  requestsMade: 843,
  duration: 360,
};
